steps:
  # Install dependencies
  - name: 'node:18'
    entrypoint: 'npm'
    args: ['install']

  # Build the Docusaurus site
  - name: 'node:18'
    entrypoint: 'npm'
    args: ['run', 'build']

  # Deploy to Google Cloud Storage (if using static hosting)
  - name: 'gcr.io/cloud-builders/gsutil'
    args: ['-m', 'rsync', '-r', '-c', '-d', './build/', 'gs://cognityv-docs-bucket/']

  # Set proper cache control headers
  - name: 'gcr.io/cloud-builders/gsutil'
    args: ['web', 'set', '-m', 'index.html', '-e', '404.html', 'gs://cognityv-docs-bucket']

# Optional: Configure timeout and machine type
timeout: '1200s'
options:
  machineType: 'E2_HIGHCPU_8' 