steps:
  # Install dependencies
  - name: 'node:18'
    entrypoint: 'npm'
    args: ['install']

  # Build the Docusaurus site
  - name: 'node:18'
    entrypoint: 'npm'
    args: ['run', 'build']

  # Deploy to App Engine
  - name: 'gcr.io/cloud-builders/gcloud'
    args: ['app', 'deploy', '--quiet']

# Configure timeout
timeout: '1200s' 